# Generated by Django 3.2.8 on 2021-10-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
